const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Fade,
		C3.Plugins.Touch,
		C3.Plugins.Audio,
		C3.Plugins.LocalStorage,
		C3.Plugins.TiledBg,
		C3.Plugins.Browser,
		C3.Behaviors.Sin,
		C3.Plugins.Spritefont2,
		C3.Behaviors.Physics,
		C3.Behaviors.destroy,
		C3.Behaviors.Pin,
		C3.Behaviors.Bullet,
		C3.Behaviors.EightDir,
		C3.Behaviors.scrollto,
		C3.Behaviors.Tween,
		C3.Behaviors.Platform,
		C3.Behaviors.solid,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.TiledBg.Acts.SetSize,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Behaviors.Platform.Acts.SetGravity,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.System.Cnds.ForEach,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.System.Cnds.PickAll,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Behaviors.Fade.Acts.RestartFade,
		C3.Plugins.Spritefont2.Acts.SetVisible,
		C3.Plugins.TiledBg.Acts.MoveAtAngle,
		C3.Plugins.Sprite.Acts.MoveAtAngle,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Browser.Acts.GoToURLWindow,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Behaviors.Fade.Acts.SetFadeOutTime,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Behaviors.Pin.Acts.Pin,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Plugins.Sprite.Exps.IID,
		C3.Behaviors.Physics.Acts.SetImmovable,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.TiledBg.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Behaviors.Bullet.Exps.Speed,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Behaviors.Pin.Cnds.IsPinned,
		C3.Behaviors.Pin.Acts.Unpin,
		C3.Plugins.Sprite.Acts.SetHeight,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Sprite.Acts.MoveToLayer,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Sprite.Cnds.CompareHeight,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.System.Exps.loadingprogress,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Plugins.System.Exps.imageloadingprogress,
		C3.Plugins.Spritefont2.Cnds.IsVisible
	];
};
self.C3_JsPropNameTable = [
	{Fade: 0},
	{Logo: 0},
	{Touch: 0},
	{Audio: 0},
	{LocalStorage: 0},
	{fadeIN: 0},
	{fadeOUT: 0},
	{Browser: 0},
	{Sine: 0},
	{btn_start: 0},
	{btn_home: 0},
	{transition: 0},
	{btn_restart: 0},
	{txt_score: 0},
	{Physics: 0},
	{DestroyOutsideLayout: 0},
	{floor_sprite: 0},
	{dust: 0},
	{Pin: 0},
	{stack: 0},
	{changeSide: 0},
	{decreaseWidth: 0},
	{Bullet: 0},
	{claw: 0},
	{"8Direction": 0},
	{ScrollTo: 0},
	{camera: 0},
	{life: 0},
	{Tween: 0},
	{txt_gameOver: 0},
	{border: 0},
	{aim: 0},
	{sky: 0},
	{grass: 0},
	{cloud: 0},
	{title: 0},
	{destroyCloud: 0},
	{Platform: 0},
	{Solid: 0},
	{stackAnimation: 0},
	{txt_bestScore: 0},
	{start_board: 0},
	{trezelogo: 0},
	{loading: 0},
	{txt_tapToStart: 0},
	{hScore: 0},
	{lastX: 0},
	{gameActive: 0},
	{score: 0},
	{speedClaw: 0},
	{Parameter0: 0},
	{load_ok: 0}
];

self.InstanceType = {
	Logo: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	fadeIN: class extends self.ITiledBackgroundInstance {},
	fadeOUT: class extends self.ITiledBackgroundInstance {},
	Browser: class extends self.IInstance {},
	btn_start: class extends self.ISpriteInstance {},
	btn_home: class extends self.ISpriteInstance {},
	transition: class extends self.ITiledBackgroundInstance {},
	btn_restart: class extends self.ISpriteInstance {},
	txt_score: class extends self.ISpriteFontInstance {},
	floor_sprite: class extends self.ITiledBackgroundInstance {},
	stack: class extends self.ISpriteInstance {},
	claw: class extends self.ISpriteInstance {},
	camera: class extends self.ISpriteInstance {},
	life: class extends self.ISpriteInstance {},
	txt_gameOver: class extends self.ISpriteFontInstance {},
	border: class extends self.ISpriteInstance {},
	aim: class extends self.ISpriteInstance {},
	sky: class extends self.ITiledBackgroundInstance {},
	grass: class extends self.ISpriteInstance {},
	dust: class extends self.ISpriteInstance {},
	cloud: class extends self.ISpriteInstance {},
	title: class extends self.ISpriteInstance {},
	destroyCloud: class extends self.ISpriteInstance {},
	stackAnimation: class extends self.ISpriteInstance {},
	txt_bestScore: class extends self.ISpriteFontInstance {},
	start_board: class extends self.ISpriteInstance {},
	trezelogo: class extends self.ISpriteInstance {},
	loading: class extends self.ITiledBackgroundInstance {},
	txt_tapToStart: class extends self.ISpriteFontInstance {}
}